# Core connectivity
CONFIG_ZMK_BLE=y
CONFIG_ZMK_USB=n
CONFIG_ZMK_KEYBOARD_NAME="KeyTop"

# BLE tuning
CONFIG_ZMK_BLE_CLEAR_BONDS_ON_START=n
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y
CONFIG_ZMK_BLE_INIT_PRIORITY=50
CONFIG_BT_MAX_CONN=5
CONFIG_BT_MAX_PAIRED=5
CONFIG_BT_PERIPHERAL_PREF_MIN_INT=6
CONFIG_BT_PERIPHERAL_PREF_MAX_INT=12
CONFIG_BT_PERIPHERAL_PREF_LATENCY=0

# Buses / peripherals
CONFIG_I2C=y
CONFIG_GPIO=y
CONFIG_INPUT=y

# Keyboard behavior
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=5
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=5
CONFIG_ZMK_POINTING=y

# Power management
CONFIG_ZMK_IDLE_TIMEOUT=300000
CONFIG_ZMK_SLEEP=n
CONFIG_ZMK_BATTERY_REPORTING=n

# Logging
CONFIG_ZMK_USB_LOGGING=n
CONFIG_WARN_DEPRECATED=n
CONFIG_LOG=y